version: '2'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - 8000:8000
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
    volumes:
      - ./flask_app:/usr/src/app/

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask_app
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro