from model.enums.mode.Mode import Mode


class SharingMode(Mode):
    CAB = 'CAB'
    TIER = 'TIER'
    EMMY = 'EMMY'
    FLINKSTER = 'FLINKSTER'
    SHARENOW = 'SHARENOW'

    ESCOOTER_SHARING = 'ESCOOTER_SHARING'
    MOPED_SHARING = 'MOPED_SHARING'
    BICYCLE_SHARING = 'BICYCLE_SHARING'
    CAR_SHARING = 'CAR_SHARING'